pod 'Firebase/Core'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProgressTrackerMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProgressTrackerMobile

  target 'ProgressTrackerMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProgressTrackerMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'ProgressTrackerMobile-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
#
#   # Pods for ProgressTrackerMobile-tvOS
#
#   target 'ProgressTrackerMobile-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
